version: '3.8'

services:
  node-api: 
    image: bitnami/postgresql
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=find-a-friend-api